# Generated by Django 5.2.6 on 2025-11-07 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gestao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11)),
                ('ativo', models.BooleanField(default=True)),
                ('eh_terceiro', models.BooleanField()),
                ('cargo', models.CharField(max_length=100)),
            ],
        ),
    ]
