# Generated by Django 5.2.6 on 2025-11-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestao',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
